apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: naming-server
  name: naming-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: naming-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: naming-server
    spec:
      containers:
      - image: tosaporn/netflix-eureka-naming-server:0.0.2-SNAPSHOT
        name: naming-server
        imagePullPolicy: Always
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: naming-server
  name: naming-server
spec:
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
  selector:
    io.kompose.service: naming-server
  sessionAffinity: None #CHANGE
  #type: LoadBalancer
  type: NodePort